name: Check master

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - run: mvn -B spotless:check
      - run: mvn -B clean org.jacoco:jacoco-maven-plugin:prepare-agent test package
      - run: mvn -B jacoco:report 
      # Sonar doesn't work due on master (works on PRs...asks for GITHUB_TOKEN ) 
#       - run: mvn -B sonar:sonar -Dsonar.github.oauth=${{ secrets.GITHUB_TOKEN }} -Dsonar.projectKey=annot8_annot8-merged -Dsonar.organization=annot8 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}
      - run: mvn deploy -DskipTests -Drepo.login==${{ secrets.OSSHR_USERNAME }} -Drepo.pwd=${{ secrets.OSSHR_PASSWORD }}
