name: Check PR

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - run: mvn -B test
      - run: mvn sonar:sonar -Dsonar.login=${{ secrets.SONAR_TOKEN }}
